; generated by Slic3r 0.5.7 on 2011-11-28 at 07:27:59

; layer_height = 0.40
; perimeters = 3
; solid_layers = 3
; fill_density = 0.3
; nozzle_diameter = 0.5
; filament_diameter = 2.92
; perimeter_speed = 30
; infill_speed = 30
; travel_speed = 100
; extrusion_width_ratio = 0
; scale = 1

M104 S17 ; set temperature
M105 ; Dummy command

M109 S17 ; wait for temperature to be reached
G90 ; use absolute coordinates
G21 ; set units to millimeters
G92 E0 ; reset extrusion distance
M82 ; use absolute distances for extrusion
M105 ; Dummy command

; filament used = 5.0mm (0.3cm3)
